[package]
name = "deploy"
version = "0.1.0"
authors = ["Jezza <jezzadabomb@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.106"
toml = "0.5.6"

rpassword = "4.0.5"

dirs = "2.0.2"
structopt = "0.3.14"
#gitlab = "=0.1209.1"
gitlab = {path = "gitlab"}
